site_name: Better-LLM
site_description: 그룹 챗 오케스트레이션 시스템 - Clean Architecture 기반 Multi-Agent 워크플로우
site_author: Better-LLM Team
site_url: https://simdaseul.github.io/better-llm/

repo_name: simdaseul/better-llm
repo_url: https://github.com/simdaseul/better-llm
edit_uri: edit/main/docs/

theme:
  name: material
  language: ko
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 라이트 모드로 전환
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: ko
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            members_order: source
            group_by_category: true
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - 홈: index.md
  - 시작하기:
    - 설치: guides/installation.md
    - 빠른 시작: guides/quickstart.md
    - 사용법: guides/usage.md
  - 아키텍처:
    - 개요: architecture.md
    - Clean Architecture: adr/0001-clean-architecture.md
    - MCP 프로토콜: adr/0002-mcp-protocol.md
    - Worker Agent: adr/0003-worker-agents.md
  - API Reference:
    - Domain:
      - Models: api/domain/models.md
      - Agents: api/domain/agents.md
      - Errors: api/domain/errors.md
    - Infrastructure:
      - Manager Client: api/infrastructure/manager.md
      - Worker Client: api/infrastructure/worker.md
      - Worker Tools: api/infrastructure/worker_tools.md
      - Config Loader: api/infrastructure/config.md
      - Storage: api/infrastructure/storage.md
      - Logging: api/infrastructure/logging.md
      - Metrics: api/infrastructure/metrics.md
      - Cache: api/infrastructure/cache.md
  - ADR:
    - 템플릿: adr/0000-template.md
    - Clean Architecture: adr/0001-clean-architecture.md
    - MCP 프로토콜: adr/0002-mcp-protocol.md
    - Worker Agent 분리: adr/0003-worker-agents.md
    - 구조화된 로깅: adr/0004-structured-logging.md
    - 비동기 메트릭 수집: adr/0005-async-metrics.md
  - 가이드:
    - 사용 사례: guides/use_cases.md
    - CLI 출력 개선: guides/cli_improvements.md
    - 안정성 및 복원력: guides/resilience.md
  - 에러 참조: errors.md
  - 문제 해결: troubleshooting.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/simdaseul/better-llm
  version:
    provider: mike

copyright: Copyright &copy; 2025 Better-LLM Team
